export { default as FirstPage } from './First/FirstPage'
export { default as StartPage } from './StartPage/StartPage'
export { default as SecondPage } from './Second/SecondPage'
export { default as ThirdPage } from './Third/ThirdPage'
export { default as ThirdPageSecond } from './Third/ThirdPageSecond'
export { default as FourthPage } from './Fourth/FourthPage'
export { default as FourthPageSecond } from './Fourth/FourthPageSecond'
export { default as FifthPage } from './Fifth/FifthPage'
export { default as SixthPage } from './Sixth/SixthPage'
export { default as SeventhPage } from './Seventh/SeventhPage'
export * from './MiddlewarePages'
